# Welcome to Colab!

In [ ]:
import numpy as np

l =[20,2,3,4,5]
A = np.array(l)
print(A)


[20  2  3  4  5]


In [ ]:
l = [1,2,3,4,5,6,7,8,9]
l[::-2]
l[1:6]
l[1:6:2]
l[:6]

[1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np
l = [[1,2,3,4,5,6,7,8,9,10],[10,20,30,40,50,60,70,80,90,100]]
A= np.array(l)
print(A)
print(A[1])
print(A[-1])
print(A[1][1])
print(A[1][-1])
print(A[-1][-2])
print(A[1][0])
A[0][0]=12
A2 = A+A
print(A2)
print([A],[A])
print([A],[A],[A])


result = np.zeros((3,3))


[[  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]
[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
20
100
90
10
[[ 24   4   6   8  10  12  14  16  18  20]
 [ 20  40  60  80 100 120 140 160 180 200]]
[array([[ 12,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])] [array([[ 12,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])]
[array([[ 12,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])] [array([[ 12,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])] [array([[ 12,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])]
